### ISSUE TITLE
Trying to compile gobohide

### ISSUE THREAD

**Issue by geaplanet** [gobolinux/GoboHide#4]
I'm trying to compile gobohide in a Debian system with a recent 5.6.14 kernel (x86_64). I applied [the patch](https://github.com/gobolinux/Recipes/tree/master/Linux/5.5.6) without problems, but when I tryed to compile the [gobohide utility](https://github.com/gobolinux/GoboHide) got this:

> make
Making all in m4
make[1]: se entra en el directorio '/tmp/GoboHide-master/m4'
make[1]: No se hace nada para 'all'.
make[1]: se sale del directorio '/tmp/GoboHide-master/m4'
Making all in po
make[1]: se entra en el directorio '/tmp/GoboHide-master/po'
make[1]: No se hace nada para 'all'.
make[1]: se sale del directorio '/tmp/GoboHide-master/po'
Making all in man
make[1]: se entra en el directorio '/tmp/GoboHide-master/man'
make[1]: No se hace nada para 'all'.
make[1]: se sale del directorio '/tmp/GoboHide-master/man'
Making all in src
make[1]: se entra en el directorio '/tmp/GoboHide-master/src'
gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DPACKAGE_NAME=\"gobohide\" -DPACKAGE_TARNAME=\"gobohide\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"gobohide\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"gobohide\" -DVERSION=\"1.0\" -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -I.     -g -O2 -I/usr/include/libnl3 -c -o gobohide.o gobohide.c
gcc  -g -O2 -I/usr/include/libnl3  -lnl-cli-3 -lnl-genl-3 -lnl-nf-3 -lnl-route-3 -lnl-3 -o gobohide gobohide.o  
/usr/bin/ld: gobohide.o: en la función `send_netlink_cmd':
/tmp/GoboHide-master/src/gobohide.c:125: referencia a `nl_cli_alloc_socket' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:126: referencia a `nl_cli_connect' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:128: referencia a `genl_ops_resolve' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:131: referencia a `genl_ctrl_resolve' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:134: referencia a `nlmsg_alloc' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:138: referencia a `genlmsg_put' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:156: referencia a `nl_send_auto_complete' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:159: referencia a `nlmsg_free' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:164: referencia a `nl_socket_modify_cb' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:168: referencia a `nl_recvmsgs_default' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:177: referencia a `nl_close' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:178: referencia a `nl_socket_free' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:145: referencia a `nla_put_u64' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:147: referencia a `nla_put_string' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:156: referencia a `nl_send_auto_complete' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:159: referencia a `nlmsg_free' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:146: referencia a `nl_geterror' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:146: referencia a `nl_cli_fatal' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:148: referencia a `nl_geterror' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:148: referencia a `nl_cli_fatal' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:157: referencia a `nl_geterror' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:157: referencia a `nl_cli_fatal' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:140: referencia a `nl_cli_fatal' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:136: referencia a `nl_cli_fatal' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:132: referencia a `nl_cli_fatal' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:129: referencia a `nl_cli_fatal' sin definir
/usr/bin/ld: gobohide.o:/tmp/GoboHide-master/src/gobohide.c:166: más referencias a `nl_cli_fatal' sin definir a continuación
/usr/bin/ld: gobohide.o: en la función `parse_cmd_list_reply':
/tmp/GoboHide-master/src/gobohide.c:65: referencia a `nla_parse' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:72: referencia a `nla_get_string' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:68: referencia a `nl_perror' sin definir
/usr/bin/ld: gobohide.o: en la función `parse_cmd_list_size':
/tmp/GoboHide-master/src/gobohide.c:49: referencia a `nla_get_u32' sin definir
/usr/bin/ld: gobohide.o: en la función `parse_cb':
/tmp/GoboHide-master/src/gobohide.c:83: referencia a `genl_handle_msg' sin definir
/usr/bin/ld: gobohide.o: en la función `init_netlink':
/tmp/GoboHide-master/src/gobohide.c:113: referencia a `genl_register_family' sin definir
/usr/bin/ld: /tmp/GoboHide-master/src/gobohide.c:115: referencia a `nl_cli_fatal' sin definir
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:396: gobohide] Error 1
make[1]: se sale del directorio '/tmp/GoboHide-master/src'
make: *** [Makefile:378: all-recursive] Error 1

>

**Comment by lucasvr** [comment]
This error indicates that the netlink symbols needed by GoboHide are not found in your system's libnl-cli-3, libnl-genl-3, libnl-nf-3, libnl-route-3, nor in libnl-3.

According to https://packages.debian.org/search?keywords=libnl, Debian splits libnl in several different packages. Make sure that you have all the libnl and libnl-dev packages installed prior to building gobohide. Let me know how that goes.

**Comment by geaplanet** [comment]
I have all installed and I think ./configure detect them correctly (sorry for the huge copy/paste):

> ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... none
checking for pkg-config... /usr/bin/pkg-config
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for ld used by GCC... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking whether NLS is requested... yes
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBNL3... yes
checking for LIBNL3_GENL... yes
checking for LIBNL3_CLI... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating m4/Makefile
config.status: creating po/Makefile.in
config.status: WARNING:  'po/Makefile.in.in' seems to ignore the --datarootdir setting
config.status: creating man/Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands
config.status: executing default-1 commands
config.status: creating po/POTFILES
config.status: creating po/Makefile

> apt search libnl
> Ordenando... Hecho
> Buscar en todo el texto... Hecho
> libnl-3-200/testing,unstable,now 3.4.0-1+b1 amd64 [instalado, automático]
>   Biblioteca para tratar con «sockets» de netlink
> 
> libnl-3-200-dbg/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   debug symbols for libnl3
> 
> libnl-3-dev/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   development library and headers for libnl-3
> 
> libnl-cli-3-200/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   library for dealing with netlink sockets - cli helpers
> 
> libnl-cli-3-dev/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   development library and headers for libnl-cli-3
> 
> libnl-genl-3-200/testing,unstable,now 3.4.0-1+b1 amd64 [instalado, automático]
>   biblioteca para tratar las conexiones netlink - netlink genérico
> 
> libnl-genl-3-dev/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   development library and headers for libnl-genl-3
> 
> libnl-idiag-3-200/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   library for dealing with netlink sockets - inetdiag interface
> 
> libnl-idiag-3-dev/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   development library and headers for libnl-genl-3
> 
> libnl-nf-3-200/testing,unstable,now 3.4.0-1+b1 amd64 [instalado, automático]
>   library for dealing with netlink sockets - netfilter interface
> 
> libnl-nf-3-dev/testing,unstable,now 3.4.0-1+b1 amd64 [instalado, automático]
>   development library and headers for libnl-nf-3
> 
> libnl-route-3-200/testing,unstable,now 3.4.0-1+b1 amd64 [instalado, automático]
>   library for dealing with netlink sockets - route interface
> 
> libnl-route-3-dev/testing,unstable,now 3.4.0-1+b1 amd64 [instalado, automático]
>   development library and headers for libnl-route-3
> 
> libnl-utils/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   Utilities for dealing with netlink sockets
> 
> libnl-xfrm-3-200/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   library for dealing with netlink sockets - package transformations
> 
> libnl-xfrm-3-dev/testing,unstable,now 3.4.0-1+b1 amd64 [instalado]
>   development library and headers for libnl-xfrm-3
> 
> libnlopt-cxx-dev/testing,unstable,now 2.6.1-8+b1 amd64 [instalado]
>   nonlinear optimization library -- development package for C++
> 
> libnlopt-cxx0/testing,unstable,now 2.6.1-8+b1 amd64 [instalado, automático]
>   nonlinear optimization library (C++ interface)
> 
> libnlopt-dev/testing,unstable,now 2.6.1-8+b1 amd64 [instalado, automático]
>   nonlinear optimization library -- development package
> 
> libnlopt-guile0/testing,unstable,now 2.6.1-8+b1 amd64 [instalado]
>   nonlinear optimization library -- Guile bindings
> 
> libnlopt0/testing,unstable,now 2.6.1-8+b1 amd64 [instalado, automático]
>   nonlinear optimization library

**Comment by lucasvr** [comment]
This seems to be related to the link order (flags before object file). I've pushed a candidate fix; please run `git pull` followed by `./autogen.sh` and let me know if it builds afterwards.

**Comment by geaplanet** [comment]
It works perfectly now :+1: 

Thanks.
